// WEEK-03/Keerthana/Handson_08/student-portal-vue/src/components/Header.vue
<template>

  <header>

    <h1>Student Portal</h1>

    <nav>

      <RouterLink to="/">Home</RouterLink> |

      <RouterLink to="/courses">Courses</RouterLink> |

      <RouterLink to="/profile">Profile</RouterLink>

    </nav>

    <p>
      Enrolled Courses: {{ store.enrolledCourses.length }}
    </p>

    <hr>

  </header>

</template>

<script setup>

import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<style scoped>

header{
  margin-bottom:20px;
}

nav{
  margin-bottom:10px;
}

</style>

// WEEK-03/Keerthana/Handson_06/student-portal-routing/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (

    <header>

      <h1>Student Portal</h1>

      <p>
        Enrolled Courses: {enrolledCourses.length}
      </p>

      <nav>

        <Link to="/">Home</Link>

        {" | "}

        <Link to="/courses">Courses</Link>

        {" | "}

        <Link to="/profile">Profile</Link>

      </nav>

      <hr />

    </header>

  );

}

export default Header;
