// WEEK-03/Keerthana/Handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard(props) {

  return (
    <div className="course-card">

      <h3>{props.name}</h3>

      <p><strong>Code:</strong> {props.code}</p>

      <p><strong>Credits:</strong> {props.credits}</p>

      <p><strong>Grade:</strong> {props.grade}</p>

      <button
        onClick={() =>
          props.onEnroll({
            id: props.id,
            name: props.name,
            code: props.code,
            credits: props.credits,
            grade: props.grade,
          })
        }
      >
        Enroll
      </button>

    </div>
  );

}

export default CourseCard;

// WEEK-03/Keerthana/Handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCardComponent {

  @Input() name: string = '';

  @Input() code: string = '';

  @Input() credits: number = 0;

  @Input() grade: string = '';

}
