// WEEK-03/Keerthana/Handson_08/student-portal-vue/src/components/CourseCard.vue
<template>

  <div>

    <h3>{{ name }}</h3>

    <p><strong>Code:</strong> {{ code }}</p>

    <p><strong>Credits:</strong> {{ credits }}</p>

    <p><strong>Grade:</strong> {{ grade }}</p>

    <button @click="$emit('enroll')">
      Enroll
    </button>

  </div>

</template>

<script setup>

defineProps({

  name: String,
  code: String,
  credits: Number,
  grade: String

})

defineEmits(['enroll'])

</script>

<style scoped>

</style>

// WEEK-03/Keerthana/Handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard(props) {

  return (
    <div className="course-card">

      <h3>{props.name}</h3>

      <p><strong>Code:</strong> {props.code}</p>

      <p><strong>Credits:</strong> {props.credits}</p>

      <p><strong>Grade:</strong> {props.grade}</p>

      <button
        onClick={() =>
          props.onEnroll({
            id: props.id,
            name: props.name,
            code: props.code,
            credits: props.credits,
            grade: props.grade,
          })
        }
      >
        Enroll
      </button>

    </div>
  );

}

export default CourseCard;
