// WEEK-03/Keerthana/Handson_08/student-portal-vue/src/components/Header.vue
<template>

  <header>

    <h1>Student Portal</h1>

    <nav>

      <RouterLink to="/">Home</RouterLink> |

      <RouterLink to="/courses">Courses</RouterLink> |

      <RouterLink to="/profile">Profile</RouterLink>

    </nav>

    <p>
      Enrolled Courses: {{ store.enrolledCourses.length }}
    </p>

    <hr>

  </header>

</template>

<script setup>

import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<style scoped>

header{
  margin-bottom:20px;
}

nav{
  margin-bottom:10px;
}

</style>

// WEEK-03/Keerthana/Handson_05/student-portal-react/src/components/Header.jsx
function Header(props) {
  return (
    <header>

      <h1>{props.siteName}</h1>

      <p>
        Enrolled Courses: {props.enrolledCount}
      </p>

      <nav>
        <a href="#">Home</a>
        <a href="#">Courses</a>
        <a href="#">Profile</a>
      </nav>

    </header>
  );
}

export default Header;
